/**
 * @file input.hpp
 * @brief Input handling system for keyboard and mouse.
 */

#ifndef WEN_CORE_INPUT_HPP_
#define WEN_CORE_INPUT_HPP_

#include "wen/wen.hpp"

#ifdef __cplusplus
extern "C" {
#endif

#define WEN_DEFINE_KEY(name, code) WEN_K##name = code

typedef enum keys_t {
  WEN_DEFINE_KEY(UNKNOWN, 0x00000000u),              /**< 0 */
  WEN_DEFINE_KEY(RETURN, 0x0000000du),               /**< '\r' */
  WEN_DEFINE_KEY(ESCAPE, 0x0000001bu),               /**< '\x1B' */
  WEN_DEFINE_KEY(BACKSPACE, 0x00000008u),            /**< '\b' */
  WEN_DEFINE_KEY(TAB, 0x00000009u),                  /**< '\t' */
  WEN_DEFINE_KEY(SPACE, 0x00000020u),                /**< ' ' */
  WEN_DEFINE_KEY(EXCLAIM, 0x00000021u),              /**< '!' */
  WEN_DEFINE_KEY(DBLAPOSTROPHE, 0x00000022u),        /**< '"' */
  WEN_DEFINE_KEY(HASH, 0x00000023u),                 /**< '#' */
  WEN_DEFINE_KEY(DOLLAR, 0x00000024u),               /**< '$' */
  WEN_DEFINE_KEY(PERCENT, 0x00000025u),              /**< '%' */
  WEN_DEFINE_KEY(AMPERSAND, 0x00000026u),            /**< '&' */
  WEN_DEFINE_KEY(APOSTROPHE, 0x00000027u),           /**< '\'' */
  WEN_DEFINE_KEY(LEFTPAREN, 0x00000028u),            /**< '(' */
  WEN_DEFINE_KEY(RIGHTPAREN, 0x00000029u),           /**< ')' */
  WEN_DEFINE_KEY(ASTERISK, 0x0000002au),             /**< '*' */
  WEN_DEFINE_KEY(PLUS, 0x0000002bu),                 /**< '+' */
  WEN_DEFINE_KEY(COMMA, 0x0000002cu),                /**< ',' */
  WEN_DEFINE_KEY(MINUS, 0x0000002du),                /**< '-' */
  WEN_DEFINE_KEY(PERIOD, 0x0000002eu),               /**< '.' */
  WEN_DEFINE_KEY(SLASH, 0x0000002fu),                /**< '/' */
  WEN_DEFINE_KEY(0, 0x00000030u),                    /**< '0' */
  WEN_DEFINE_KEY(1, 0x00000031u),                    /**< '1' */
  WEN_DEFINE_KEY(2, 0x00000032u),                    /**< '2' */
  WEN_DEFINE_KEY(3, 0x00000033u),                    /**< '3' */
  WEN_DEFINE_KEY(4, 0x00000034u),                    /**< '4' */
  WEN_DEFINE_KEY(5, 0x00000035u),                    /**< '5' */
  WEN_DEFINE_KEY(6, 0x00000036u),                    /**< '6' */
  WEN_DEFINE_KEY(7, 0x00000037u),                    /**< '7' */
  WEN_DEFINE_KEY(8, 0x00000038u),                    /**< '8' */
  WEN_DEFINE_KEY(9, 0x00000039u),                    /**< '9' */
  WEN_DEFINE_KEY(COLON, 0x0000003au),                /**< ':' */
  WEN_DEFINE_KEY(SEMICOLON, 0x0000003bu),            /**< ',' */
  WEN_DEFINE_KEY(LESS, 0x0000003cu),                 /**< '<' */
  WEN_DEFINE_KEY(EQUALS, 0x0000003du),               /**< '=' */
  WEN_DEFINE_KEY(GREATER, 0x0000003eu),              /**< '>' */
  WEN_DEFINE_KEY(QUESTION, 0x0000003fu),             /**< '?' */
  WEN_DEFINE_KEY(AT, 0x00000040u),                   /**< '@' */
  WEN_DEFINE_KEY(LEFTBRACKET, 0x0000005bu),          /**< '[' */
  WEN_DEFINE_KEY(BACKSLASH, 0x0000005cu),            /**< '\\' */
  WEN_DEFINE_KEY(RIGHTBRACKET, 0x0000005du),         /**< ']' */
  WEN_DEFINE_KEY(CARET, 0x0000005eu),                /**< '^' */
  WEN_DEFINE_KEY(UNDERSCORE, 0x0000005fu),           /**< '_' */
  WEN_DEFINE_KEY(GRAVE, 0x00000060u),                /**< '`' */
  WEN_DEFINE_KEY(A, 0x00000061u),                    /**< 'a' */
  WEN_DEFINE_KEY(B, 0x00000062u),                    /**< 'b' */
  WEN_DEFINE_KEY(C, 0x00000063u),                    /**< 'c' */
  WEN_DEFINE_KEY(D, 0x00000064u),                    /**< 'd' */
  WEN_DEFINE_KEY(E, 0x00000065u),                    /**< 'e' */
  WEN_DEFINE_KEY(F, 0x00000066u),                    /**< 'f' */
  WEN_DEFINE_KEY(G, 0x00000067u),                    /**< 'g' */
  WEN_DEFINE_KEY(H, 0x00000068u),                    /**< 'h' */
  WEN_DEFINE_KEY(I, 0x00000069u),                    /**< 'i' */
  WEN_DEFINE_KEY(J, 0x0000006au),                    /**< 'j' */
  WEN_DEFINE_KEY(K, 0x0000006bu),                    /**< 'k' */
  WEN_DEFINE_KEY(L, 0x0000006cu),                    /**< 'l' */
  WEN_DEFINE_KEY(M, 0x0000006du),                    /**< 'm' */
  WEN_DEFINE_KEY(N, 0x0000006eu),                    /**< 'n' */
  WEN_DEFINE_KEY(O, 0x0000006fu),                    /**< 'o' */
  WEN_DEFINE_KEY(P, 0x00000070u),                    /**< 'p' */
  WEN_DEFINE_KEY(Q, 0x00000071u),                    /**< 'q' */
  WEN_DEFINE_KEY(R, 0x00000072u),                    /**< 'r' */
  WEN_DEFINE_KEY(S, 0x00000073u),                    /**< 's' */
  WEN_DEFINE_KEY(T, 0x00000074u),                    /**< 't' */
  WEN_DEFINE_KEY(U, 0x00000075u),                    /**< 'u' */
  WEN_DEFINE_KEY(V, 0x00000076u),                    /**< 'v' */
  WEN_DEFINE_KEY(W, 0x00000077u),                    /**< 'w' */
  WEN_DEFINE_KEY(X, 0x00000078u),                    /**< 'x' */
  WEN_DEFINE_KEY(Y, 0x00000079u),                    /**< 'y' */
  WEN_DEFINE_KEY(Z, 0x0000007au),                    /**< 'z' */
  WEN_DEFINE_KEY(LEFTBRACE, 0x0000007bu),            /**< '{' */
  WEN_DEFINE_KEY(PIPE, 0x0000007cu),                 /**< '|' */
  WEN_DEFINE_KEY(RIGHTBRACE, 0x0000007du),           /**< '}' */
  WEN_DEFINE_KEY(TILDE, 0x0000007eu),                /**< '~' */
  WEN_DEFINE_KEY(DELETE, 0x0000007fu),               /**< '\x7F' */
  WEN_DEFINE_KEY(PLUSMINUS, 0x000000b1u),            /**< '\xB1' */
  WEN_DEFINE_KEY(CAPSLOCK, 0x40000039u),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CAPSLOCK) */
  WEN_DEFINE_KEY(F1, 0x4000003au),                   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F1) */
  WEN_DEFINE_KEY(F2, 0x4000003bu),                   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F2) */
  WEN_DEFINE_KEY(F3, 0x4000003cu),                   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F3) */
  WEN_DEFINE_KEY(F4, 0x4000003du),                   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F4) */
  WEN_DEFINE_KEY(F5, 0x4000003eu),                   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F5) */
  WEN_DEFINE_KEY(F6, 0x4000003fu),                   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F6) */
  WEN_DEFINE_KEY(F7, 0x40000040u),                   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F7) */
  WEN_DEFINE_KEY(F8, 0x40000041u),                   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F8) */
  WEN_DEFINE_KEY(F9, 0x40000042u),                   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F9) */
  WEN_DEFINE_KEY(F10, 0x40000043u),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F10) */
  WEN_DEFINE_KEY(F11, 0x40000044u),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F11) */
  WEN_DEFINE_KEY(F12, 0x40000045u),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F12) */
  WEN_DEFINE_KEY(PRINTSCREEN, 0x40000046u),          /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRINTSCREEN) */
  WEN_DEFINE_KEY(SCROLLLOCK, 0x40000047u),           /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SCROLLLOCK) */
  WEN_DEFINE_KEY(PAUSE, 0x40000048u),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAUSE) */
  WEN_DEFINE_KEY(INSERT, 0x40000049u),               /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_INSERT) */
  WEN_DEFINE_KEY(HOME, 0x4000004au),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HOME) */
  WEN_DEFINE_KEY(PAGEUP, 0x4000004bu),               /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEUP) */
  WEN_DEFINE_KEY(END, 0x4000004du),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_END) */
  WEN_DEFINE_KEY(PAGEDOWN, 0x4000004eu),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEDOWN) */
  WEN_DEFINE_KEY(RIGHT, 0x4000004fu),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RIGHT) */
  WEN_DEFINE_KEY(LEFT, 0x40000050u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LEFT) */
  WEN_DEFINE_KEY(DOWN, 0x40000051u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DOWN) */
  WEN_DEFINE_KEY(UP, 0x40000052u),                   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UP) */
  WEN_DEFINE_KEY(NUMLOCKCLEAR, 0x40000053u),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR) */
  WEN_DEFINE_KEY(KP_DIVIDE, 0x40000054u),            /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE) */
  WEN_DEFINE_KEY(KP_MULTIPLY, 0x40000055u),          /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY) */
  WEN_DEFINE_KEY(KP_MINUS, 0x40000056u),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS) */
  WEN_DEFINE_KEY(KP_PLUS, 0x40000057u),              /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS) */
  WEN_DEFINE_KEY(KP_ENTER, 0x40000058u),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_ENTER) */
  WEN_DEFINE_KEY(KP_1, 0x40000059u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_1) */
  WEN_DEFINE_KEY(KP_2, 0x4000005au),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_2) */
  WEN_DEFINE_KEY(KP_3, 0x4000005bu),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_3) */
  WEN_DEFINE_KEY(KP_4, 0x4000005cu),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_4) */
  WEN_DEFINE_KEY(KP_5, 0x4000005du),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_5) */
  WEN_DEFINE_KEY(KP_6, 0x4000005eu),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_6) */
  WEN_DEFINE_KEY(KP_7, 0x4000005fu),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_7) */
  WEN_DEFINE_KEY(KP_8, 0x40000060u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_8) */
  WEN_DEFINE_KEY(KP_9, 0x40000061u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_9) */
  WEN_DEFINE_KEY(KP_0, 0x40000062u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_0) */
  WEN_DEFINE_KEY(KP_PERIOD, 0x40000063u),            /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD) */
  WEN_DEFINE_KEY(APPLICATION, 0x40000065u),          /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APPLICATION) */
  WEN_DEFINE_KEY(POWER, 0x40000066u),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_POWER) */
  WEN_DEFINE_KEY(KP_EQUALS, 0x40000067u),            /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALS) */
  WEN_DEFINE_KEY(F13, 0x40000068u),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F13) */
  WEN_DEFINE_KEY(F14, 0x40000069u),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F14) */
  WEN_DEFINE_KEY(F15, 0x4000006au),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F15) */
  WEN_DEFINE_KEY(F16, 0x4000006bu),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F16) */
  WEN_DEFINE_KEY(F17, 0x4000006cu),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F17) */
  WEN_DEFINE_KEY(F18, 0x4000006du),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F18) */
  WEN_DEFINE_KEY(F19, 0x4000006eu),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F19) */
  WEN_DEFINE_KEY(F20, 0x4000006fu),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F20) */
  WEN_DEFINE_KEY(F21, 0x40000070u),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F21) */
  WEN_DEFINE_KEY(F22, 0x40000071u),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F22) */
  WEN_DEFINE_KEY(F23, 0x40000072u),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F23) */
  WEN_DEFINE_KEY(F24, 0x40000073u),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F24) */
  WEN_DEFINE_KEY(EXECUTE, 0x40000074u),              /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXECUTE) */
  WEN_DEFINE_KEY(HELP, 0x40000075u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HELP) */
  WEN_DEFINE_KEY(MENU, 0x40000076u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MENU) */
  WEN_DEFINE_KEY(SELECT, 0x40000077u),               /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SELECT) */
  WEN_DEFINE_KEY(STOP, 0x40000078u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_STOP) */
  WEN_DEFINE_KEY(AGAIN, 0x40000079u),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AGAIN) */
  WEN_DEFINE_KEY(UNDO, 0x4000007au),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UNDO) */
  WEN_DEFINE_KEY(CUT, 0x4000007bu),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CUT) */
  WEN_DEFINE_KEY(COPY, 0x4000007cu),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COPY) */
  WEN_DEFINE_KEY(PASTE, 0x4000007du),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PASTE) */
  WEN_DEFINE_KEY(FIND, 0x4000007eu),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_FIND) */
  WEN_DEFINE_KEY(MUTE, 0x4000007fu),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MUTE) */
  WEN_DEFINE_KEY(VOLUMEUP, 0x40000080u),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEUP) */
  WEN_DEFINE_KEY(VOLUMEDOWN, 0x40000081u),           /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEDOWN) */
  WEN_DEFINE_KEY(KP_COMMA, 0x40000085u),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COMMA) */
  WEN_DEFINE_KEY(KP_EQUALSAS400, 0x40000086u),       /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALSAS400) */
  WEN_DEFINE_KEY(ALTERASE, 0x40000099u),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ALTERASE) */
  WEN_DEFINE_KEY(SYSREQ, 0x4000009au),               /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SYSREQ) */
  WEN_DEFINE_KEY(CANCEL, 0x4000009bu),               /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CANCEL) */
  WEN_DEFINE_KEY(CLEAR, 0x4000009cu),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEAR) */
  WEN_DEFINE_KEY(PRIOR, 0x4000009du),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRIOR) */
  WEN_DEFINE_KEY(RETURN2, 0x4000009eu),              /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RETURN2) */
  WEN_DEFINE_KEY(SEPARATOR, 0x4000009fu),            /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SEPARATOR) */
  WEN_DEFINE_KEY(OUT, 0x400000a0u),                  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OUT) */
  WEN_DEFINE_KEY(OPER, 0x400000a1u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OPER) */
  WEN_DEFINE_KEY(CLEARAGAIN, 0x400000a2u),           /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEARAGAIN) */
  WEN_DEFINE_KEY(CRSEL, 0x400000a3u),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CRSEL) */
  WEN_DEFINE_KEY(EXSEL, 0x400000a4u),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXSEL) */
  WEN_DEFINE_KEY(KP_00, 0x400000b0u),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_00) */
  WEN_DEFINE_KEY(KP_000, 0x400000b1u),               /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_000) */
  WEN_DEFINE_KEY(THOUSANDSSEPARATOR, 0x400000b2u),   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_THOUSANDSSEPARATOR) */
  WEN_DEFINE_KEY(DECIMALSEPARATOR, 0x400000b3u),     /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DECIMALSEPARATOR) */
  WEN_DEFINE_KEY(CURRENCYUNIT, 0x400000b4u),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYUNIT) */
  WEN_DEFINE_KEY(CURRENCYSUBUNIT, 0x400000b5u),      /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYSUBUNIT) */
  WEN_DEFINE_KEY(KP_LEFTPAREN, 0x400000b6u),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTPAREN) */
  WEN_DEFINE_KEY(KP_RIGHTPAREN, 0x400000b7u),        /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTPAREN) */
  WEN_DEFINE_KEY(KP_LEFTBRACE, 0x400000b8u),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTBRACE) */
  WEN_DEFINE_KEY(KP_RIGHTBRACE, 0x400000b9u),        /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTBRACE) */
  WEN_DEFINE_KEY(KP_TAB, 0x400000bau),               /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_TAB) */
  WEN_DEFINE_KEY(KP_BACKSPACE, 0x400000bbu),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BACKSPACE) */
  WEN_DEFINE_KEY(KP_A, 0x400000bcu),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_A) */
  WEN_DEFINE_KEY(KP_B, 0x400000bdu),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_B) */
  WEN_DEFINE_KEY(KP_C, 0x400000beu),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_C) */
  WEN_DEFINE_KEY(KP_D, 0x400000bfu),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_D) */
  WEN_DEFINE_KEY(KP_E, 0x400000c0u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_E) */
  WEN_DEFINE_KEY(KP_F, 0x400000c1u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_F) */
  WEN_DEFINE_KEY(KP_XOR, 0x400000c2u),               /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_XOR) */
  WEN_DEFINE_KEY(KP_POWER, 0x400000c3u),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_POWER) */
  WEN_DEFINE_KEY(KP_PERCENT, 0x400000c4u),           /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERCENT) */
  WEN_DEFINE_KEY(KP_LESS, 0x400000c5u),              /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LESS) */
  WEN_DEFINE_KEY(KP_GREATER, 0x400000c6u),           /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_GREATER) */
  WEN_DEFINE_KEY(KP_AMPERSAND, 0x400000c7u),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AMPERSAND) */
  WEN_DEFINE_KEY(KP_DBLAMPERSAND, 0x400000c8u),      /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLAMPERSAND) */
  WEN_DEFINE_KEY(KP_VERTICALBAR, 0x400000c9u),       /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_VERTICALBAR) */
  WEN_DEFINE_KEY(KP_DBLVERTICALBAR, 0x400000cau),    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLVERTICALBAR) */
  WEN_DEFINE_KEY(KP_COLON, 0x400000cbu),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COLON) */
  WEN_DEFINE_KEY(KP_HASH, 0x400000ccu),              /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HASH) */
  WEN_DEFINE_KEY(KP_SPACE, 0x400000cdu),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_SPACE) */
  WEN_DEFINE_KEY(KP_AT, 0x400000ceu),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AT) */
  WEN_DEFINE_KEY(KP_EXCLAM, 0x400000cfu),            /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EXCLAM) */
  WEN_DEFINE_KEY(KP_MEMSTORE, 0x400000d0u),          /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSTORE) */
  WEN_DEFINE_KEY(KP_MEMRECALL, 0x400000d1u),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMRECALL) */
  WEN_DEFINE_KEY(KP_MEMCLEAR, 0x400000d2u),          /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMCLEAR) */
  WEN_DEFINE_KEY(KP_MEMADD, 0x400000d3u),            /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMADD) */
  WEN_DEFINE_KEY(KP_MEMSUBTRACT, 0x400000d4u),       /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSUBTRACT) */
  WEN_DEFINE_KEY(KP_MEMMULTIPLY, 0x400000d5u),       /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMMULTIPLY) */
  WEN_DEFINE_KEY(KP_MEMDIVIDE, 0x400000d6u),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMDIVIDE) */
  WEN_DEFINE_KEY(KP_PLUSMINUS, 0x400000d7u),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUSMINUS) */
  WEN_DEFINE_KEY(KP_CLEAR, 0x400000d8u),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEAR) */
  WEN_DEFINE_KEY(KP_CLEARENTRY, 0x400000d9u),        /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEARENTRY) */
  WEN_DEFINE_KEY(KP_BINARY, 0x400000dau),            /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BINARY) */
  WEN_DEFINE_KEY(KP_OCTAL, 0x400000dbu),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_OCTAL) */
  WEN_DEFINE_KEY(KP_DECIMAL, 0x400000dcu),           /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DECIMAL) */
  WEN_DEFINE_KEY(KP_HEXADECIMAL, 0x400000ddu),       /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HEXADECIMAL) */
  WEN_DEFINE_KEY(LCTRL, 0x400000e0u),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LCTRL) */
  WEN_DEFINE_KEY(LSHIFT, 0x400000e1u),               /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LSHIFT) */
  WEN_DEFINE_KEY(LALT, 0x400000e2u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LALT) */
  WEN_DEFINE_KEY(LGUI, 0x400000e3u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LGUI) */
  WEN_DEFINE_KEY(RCTRL, 0x400000e4u),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RCTRL) */
  WEN_DEFINE_KEY(RSHIFT, 0x400000e5u),               /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RSHIFT) */
  WEN_DEFINE_KEY(RALT, 0x400000e6u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RALT) */
  WEN_DEFINE_KEY(RGUI, 0x400000e7u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RGUI) */
  WEN_DEFINE_KEY(MODE, 0x40000101u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MODE) */
  WEN_DEFINE_KEY(SLEEP, 0x40000102u),                /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SLEEP) */
  WEN_DEFINE_KEY(WAKE, 0x40000103u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_WAKE) */
  WEN_DEFINE_KEY(CHANNEL_INCREMENT, 0x40000104u),    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_INCREMENT) */
  WEN_DEFINE_KEY(CHANNEL_DECREMENT, 0x40000105u),    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_DECREMENT) */
  WEN_DEFINE_KEY(MEDIA_PLAY, 0x40000106u),           /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY) */
  WEN_DEFINE_KEY(MEDIA_PAUSE, 0x40000107u),          /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PAUSE) */
  WEN_DEFINE_KEY(MEDIA_RECORD, 0x40000108u),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_RECORD) */
  WEN_DEFINE_KEY(MEDIA_FAST_FORWARD, 0x40000109u),   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_FAST_FORWARD) */
  WEN_DEFINE_KEY(MEDIA_REWIND, 0x4000010au),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_REWIND) */
  WEN_DEFINE_KEY(MEDIA_NEXT_TRACK, 0x4000010bu),     /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_NEXT_TRACK) */
  WEN_DEFINE_KEY(MEDIA_PREVIOUS_TRACK, 0x4000010cu), /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PREVIOUS_TRACK) */
  WEN_DEFINE_KEY(MEDIA_STOP, 0x4000010du),           /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_STOP) */
  WEN_DEFINE_KEY(MEDIA_EJECT, 0x4000010eu),          /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_EJECT) */
  WEN_DEFINE_KEY(MEDIA_PLAY_PAUSE, 0x4000010fu),     /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY_PAUSE) */
  WEN_DEFINE_KEY(MEDIA_SELECT, 0x40000110u),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_SELECT) */
  WEN_DEFINE_KEY(AC_NEW, 0x40000111u),               /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_NEW) */
  WEN_DEFINE_KEY(AC_OPEN, 0x40000112u),              /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_OPEN) */
  WEN_DEFINE_KEY(AC_CLOSE, 0x40000113u),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_CLOSE) */
  WEN_DEFINE_KEY(AC_EXIT, 0x40000114u),              /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_EXIT) */
  WEN_DEFINE_KEY(AC_SAVE, 0x40000115u),              /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SAVE) */
  WEN_DEFINE_KEY(AC_PRINT, 0x40000116u),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PRINT) */
  WEN_DEFINE_KEY(AC_PROPERTIES, 0x40000117u),        /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PROPERTIES) */
  WEN_DEFINE_KEY(AC_SEARCH, 0x40000118u),            /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SEARCH) */
  WEN_DEFINE_KEY(AC_HOME, 0x40000119u),              /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_HOME) */
  WEN_DEFINE_KEY(AC_BACK, 0x4000011au),              /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BACK) */
  WEN_DEFINE_KEY(AC_FORWARD, 0x4000011bu),           /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_FORWARD) */
  WEN_DEFINE_KEY(AC_STOP, 0x4000011cu),              /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_STOP) */
  WEN_DEFINE_KEY(AC_REFRESH, 0x4000011du),           /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_REFRESH) */
  WEN_DEFINE_KEY(AC_BOOKMARKS, 0x4000011eu),         /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS) */
  WEN_DEFINE_KEY(SOFTLEFT, 0x4000011fu),             /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTLEFT) */
  WEN_DEFINE_KEY(SOFTRIGHT, 0x40000120u),            /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTRIGHT) */
  WEN_DEFINE_KEY(CALL, 0x40000121u),                 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CALL) */
  WEN_DEFINE_KEY(ENDCALL, 0x40000122u),              /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ENDCALL) */
  WEN_DEFINE_KEY(LEFT_TAB, 0x20000001u),             /**< Extended key Left Tab */
  WEN_DEFINE_KEY(LEVEL5_SHIFT, 0x20000002u),         /**< Extended key Level 5 Shift */
  WEN_DEFINE_KEY(MULTI_KEY_COMPOSE, 0x20000003u),    /**< Extended key Multi-key Compose */
  WEN_DEFINE_KEY(LMETA, 0x20000004u),                /**< Extended key Left Meta */
  WEN_DEFINE_KEY(RMETA, 0x20000005u),                /**< Extended key Right Meta */
  WEN_DEFINE_KEY(LHYPER, 0x20000006u),               /**< Extended key Left Hyper */
  WEN_DEFINE_KEY(RHYPER, 0x20000007u),               /**< Extended key Right Hyper */

  WEN_KEYS_COUNT,
} keys_t;

/**
 *
 */
typedef enum buttons_t {
  BUTTON_LEFT,   /**< Left mouse button. */
  BUTTON_RIGHT,  /**< Right mouse button. */
  BUTTON_MIDDLE, /**< Middle mouse button. */
  BUTTON_COUNT,  /**< Total number of buttons. */
} buttons_t;

/**
 * @brief Initializes the input system.
 * This function must be called before using any input-related functions.
 */
void input_system_initialize();

/**
 * @brief Shuts down the input system.
 * Cleans up any allocated resources related to input handling.
 */
void input_system_shutdown();

/**
 * @brief Updates the input system.
 * This function should be called every frame to process input events.
 * @param dt Time delta (in seconds) since last update.
 */
void input_system_update(float dt);

/**
 * @brief
 * @param keys_t
 */
WEN_API bool wen_input_is_key_down(keys_t key_code_);

/**
 * @brief
 * @param keys_t
 */
WEN_API bool wen_input_is_key_up(keys_t key_code_);

/**
 * @brief
 * @param keys_t
 */
WEN_API bool wen_input_was_key_down(keys_t key_code_);

/**
 * @brief
 * @param keys_t
 */
WEN_API bool wen_input_was_key_up(keys_t key_code_);

/**
 * @brief
 * @param keys_t
 * @param bool
 */
void input_process_key(keys_t key, bool is_pressed);

/**
 * @brief
 * @param button_
 */
WEN_API bool wen_input_is_button_down(buttons_t button_);

/**
 * @brief
 * @param button_
 */
WEN_API bool wen_input_is_button_up(buttons_t button_);

/**
 * @brief
 * @param button_
 */
WEN_API bool wen_input_was_button_down(buttons_t button_);

/**
 * @brief
 * @param button_
 */
WEN_API bool wen_input_was_button_up(buttons_t button_);

/**
 * @brief
 * @param int32_t*
 * @param int32_t*
 */
WEN_API void wen_input_get_mouse_pos(int32_t* x, int32_t* y);

/**
 * @brief
 * @param int32_t*
 * @param int32_t*
 */
WEN_API void wen_input_get_prev_mouse_pos(int32_t* x, int32_t* y);

/**
 * @def
 * @param button_t
 * @param bool
 */
void input_process_button(buttons_t button, bool is_pressed);

/**
 * @def input_process_mouse_move
 * @param int16_t
 * @param int16_t
 */
void input_process_mouse_move(int16_t x, int16_t y);

/**
 * @def input_process_mouse_move
 * @param int8_t
 */
void input_process_mouse_wheel(int8_t z_delta);

#ifdef __cplusplus
}
#endif

#endif // WEN_CORE_INPUT_HPP_
